GestaoTarefasIPG/Controllers/EscolasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers {
    public class EscolasController : Controller {
        private readonly IPGDbContext _context;

        private const int NUMERO_ESCOLAS_POR_PAGINA = 10;
        private const int NUMERO_PAGINAS_ANTES_E_DEPOIS = 2;

        public EscolasController(IPGDbContext context) {
            _context = context;
        }

        // GET: Escolas
        //public async Task<IActionResult> Index(int page = 1){

        //public IActionResult Index(int page=1, string searchString = null) {
        public async Task<IActionResult> Index(int page = 1, string searchString = "", string sort = "true") {
            var Escola = from p in _context.Escola select p;

            if (!String.IsNullOrEmpty(searchString)) {
                Escola = Escola.Where(p => p.NomeEscola.Contains(searchString));
            }


            //return View(await _context.Escola.ToListAsync());
            decimal numeroEscolas = _context.Escola.Count();

            EscolasViewModel vm = new EscolasViewModel {
                Sort = sort,

                CurrentPage = page,

                FirstPageShow = Math.Max(1, page - NUMERO_PAGINAS_ANTES_E_DEPOIS),

                TotalPages = (int)Math.Ceiling(numeroEscolas / NUMERO_ESCOLAS_POR_PAGINA)
            };

            if (sort.Equals("true")) {
                vm.Escolas = Escola.OrderBy(p => p.NomeEscola).Skip((page - 1) * NUMERO_ESCOLAS_POR_PAGINA).Take(NUMERO_ESCOLAS_POR_PAGINA);
            } else {
                vm.Escolas = Escola.OrderByDescending(p => p.NomeEscola).Skip((page - 1) * NUMERO_ESCOLAS_POR_PAGINA).Take(NUMERO_ESCOLAS_POR_PAGINA);
            }

            vm.StringProcura = searchString;

            vm.LastPageShow = Math.Min(vm.TotalPages, page + NUMERO_PAGINAS_ANTES_E_DEPOIS);

            return View(vm);
        }

        // GET: Escolas/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var escola = await _context.Escola
                .FirstOrDefaultAsync(m => m.EscolaId == id);
            if (escola == null) {
                return NotFound();
            }

            return View(escola);
        }

        // GET: Escolas/Create
        [Authorize(Policy = "Gerir")]

        public IActionResult Create() {
            return View();
        }

        // POST: Escolas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EscolaId,NomeEscola,Telefone")] Escola escola) {
            if (ModelState.IsValid) {

                if (_context.Escola.FirstOrDefault(p => p.NomeEscola == escola.NomeEscola) == null) {
                    _context.Add(escola);
                    
                 if   (_context.Escola.Select(p => p.Telefone == escola.Telefone) == null) {
                        _context.Add(escola);
                    }
                    await _context.SaveChangesAsync();
                    ViewBag.Title = "A Escola foi criada com sucesso";

                    return View("Success");
                } else {


                    ModelState.AddModelError("NomeEscola","Não é possível adicionar escolas com nomes repetidos.");
                    ModelState.AddModelError("Telefone", "Não é possível adicionar escolas com nomes repetidos.");
                    return View(escola);

                   


                }


            }
            return View(escola);
        }


        // GET: Escolas/Edit/5
        [Authorize(Policy = "Gerir")]
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }

            var escola = await _context.Escola.FindAsync(id);
            if (escola == null) {
                return NotFound();
            }
            return View(escola);
        }

        // POST: Escolas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EscolaId,NomeEscola,Telefone")] Escola escola) {
            if (id != escola.EscolaId) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    if (_context.Escola.FirstOrDefault(p => p.NomeEscola == escola.NomeEscola) == null) {
                        _context.Update(escola);
                        await _context.SaveChangesAsync();
                        ViewBag.Title = "A Escola foi editada com sucesso";

                        return View("Success");
                    } else {
                        
                        ModelState.AddModelError("NomeEscola", "Não é possível adicionar escolas com nomes repetidos.");
                        return View(escola);
                        {

                        }
                       

                     
                    }
                } catch (DbUpdateConcurrencyException) {
                    if (!EscolaExists(escola.EscolaId)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));

                ViewBag.Title = "Escola editada com sucesso";
                //ViewBag.Message = "A escola foi editada com sucesso";

                return View("Success");
            }
            return View(escola);
        }

        // GET: Escolas/Delete/5
        [Authorize(Policy = "Gerir")]
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }

            var escola = await _context.Escola
                .FirstOrDefaultAsync(m => m.EscolaId == id);
            if (escola == null) {
                return NotFound();
            }

            return View(escola);
        }

        // POST: Escolas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var escola = await _context.Escola.FindAsync(id);
            _context.Escola.Remove(escola);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));

            ViewBag.Title = "Escola apagada com sucesso";
            //ViewBag.Message = "A escola foi apagada com sucesso";

            return View("Success");
        }

        private bool EscolaExists(int id) {
            return _context.Escola.Any(e => e.EscolaId == id);
        }
    }
}

GestaoTarefasIPG/Controllers/FuncaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GestaoTarefasIPG.Models;
using Microsoft.AspNetCore.Authorization;

namespace GestaoTarefasIPG.Controllers {
    public class FuncaoController : Controller {
        private readonly IPGDbContext _context;

        private const int NUMERO_FUNCOES_POR_PAGINA = 10;
        private const int NUMERO_PAGINAS_ANTES_E_DEPOIS = 2;

        public FuncaoController(IPGDbContext context) {
            _context = context;
        }

        // GET: Funcao
        //public async Task<IActionResult> Index(int page = 1){

        public async Task<IActionResult> Index(int page = 1, string searchString = "", string sort = "true") {
            var Funcao = from p in _context.Funcao select p;

            if (!String.IsNullOrEmpty(searchString)) {
                Funcao = Funcao.Where(p => p.NomeFuncao.Contains(searchString));
            }


            //return View(await _context.Escola.ToListAsync());
            decimal numeroFuncoes = _context.Funcao.Count();

            FuncoesViewModel vm = new FuncoesViewModel {
                Sort = sort,

                PaginaAtual = page,

                PrimeiraPagina = Math.Max(1, page - NUMERO_PAGINAS_ANTES_E_DEPOIS),

                TotalPaginas = (int)Math.Ceiling(numeroFuncoes / NUMERO_FUNCOES_POR_PAGINA)
            };

            if (sort.Equals("true")) {
                vm.Funcoes = Funcao.OrderBy(p => p.NomeFuncao).Skip((page - 1) * NUMERO_FUNCOES_POR_PAGINA).Take(NUMERO_FUNCOES_POR_PAGINA);
            } else {
                vm.Funcoes = Funcao.OrderByDescending(p => p.NomeFuncao).Skip((page - 1) * NUMERO_FUNCOES_POR_PAGINA).Take(NUMERO_FUNCOES_POR_PAGINA);
            }

            vm.UltimaPagina = Math.Min(vm.TotalPaginas, page + NUMERO_PAGINAS_ANTES_E_DEPOIS);
            vm.StringProcura = searchString;

            return View(vm);
        }

        // GET: Funcao/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var funcao = await _context.Funcao
                .FirstOrDefaultAsync(m => m.FuncaoId == id);
            if (funcao == null) {
                return NotFound();
            }

            return View(funcao);
        }

        // GET: Funcao/Create
        [Authorize(Policy = "Gerir")]
        public IActionResult Create() {
            return View();
        }

        // POST: Funcao/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FuncaoId,NomeFuncao")] Funcao funcao) {
            if (_context.Funcao.FirstOrDefault(p => p.NomeFuncao == funcao.NomeFuncao) == null) {
                _context.Add(funcao);
                await _context.SaveChangesAsync();
                ViewBag.Title = "A Função foi criada com sucesso";

                return View("Success");
            } else {


                ModelState.AddModelError("NomeFuncao", "Não é possível adicionar nomes repetidos.");
                return View(funcao);


            }
        
            return View(funcao);
        }

        // GET: Funcao/Edit/5
        [Authorize(Policy = "Gerir")]
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }

            var funcao = await _context.Funcao.FindAsync(id);
            if (funcao == null) {
                return NotFound();
            }
            return View(funcao);
        }

        // POST: Funcao/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FuncaoId,NomeFuncao")] Funcao funcao) {
            if (id != funcao.FuncaoId) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                    try {
                        if (_context.Funcao.FirstOrDefault(p => p.NomeFuncao == funcao.NomeFuncao) == null) {
                            _context.Update(funcao);
                            await _context.SaveChangesAsync();
                            ViewBag.Title = "A Função foi editado com sucesso";

                            return View("Success");
                        } else {
                            
                            ModelState.AddModelError("NomeFuncao", "Não é possível adicionar funções com nomes repetidos.");
                            return View(funcao);
                            {

                            }
                          
                        }
                    } catch (DbUpdateConcurrencyException) {
                    if (!FuncaoExists(funcao.FuncaoId)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));

                ViewBag.Title = "Funcão editada com sucesso";
                //ViewBag.Message = "A Funcão foi editada com sucesso";

                return View("Success");
            }
            return View(funcao);
        }

        // GET: Funcao/Delete/5
        [Authorize(Policy = "Gerir")]
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }

            var funcao = await _context.Funcao
                .FirstOrDefaultAsync(m => m.FuncaoId == id);
            if (funcao == null) {
                return NotFound();
            }

            return View(funcao);
        }

        // POST: Funcao/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var funcao = await _context.Funcao.FindAsync(id);
            _context.Funcao.Remove(funcao);
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));

            ViewBag.Title = "Função apagada com sucesso";
            //ViewBag.Message = "A Funcão foi apagada com sucesso";

            return View("Success");
        }

        private bool FuncaoExists(int id) {
            return _context.Funcao.Any(e => e.FuncaoId == id);
        }
    }
}

GestaoTarefasIPG/Views/Shared/_Layout.cshtml
    <!DOCTYPE html>
<html lang="pt">
<head>
    <!--

    

   
    
    
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="css/clean-blog.min.css" rel="stylesheet">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestaoTarefasIPG</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Departamento" asp-action="">Departamento</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Escolas" asp-action="">Escolas</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Funcao" asp-action="">Funções</a>
                    </li>
                    <partial name="_LoginPartial" />
                </ul>
            </div>
        </div>
    </nav>

    <header class="masthead"  style="background-image: url('images/IPG.jpg')" >
        <div class="overlay"  ></div>
        
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Gestão de Tarefas</h1>
                        <span class="subheading">Instituto Politécnico da Guarda</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

   
                    <div class="container">
                        <main role="main" class="pb-3">
                            @RenderBody()
                        </main>
                    </div>
                    <footer>
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-8 col-md-10 mx-auto">
                                    &copy; 2020 - GestaoTarefasIPG - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                                </div>
                            </div>
                        </div>
                    </footer>
        
                    <script src="~/lib/jquery/dist/jquery.min.js"></script>
                    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
                    <script src="~/js/site.js" asp-append-version="true"></script>
                    @RenderSection("Scripts", required: false)
</body>
</html>